<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_rad2deg" Id="{3ccf238e-71a2-4e52-88ef-1badeef3e816}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_rad2deg : LREAL
VAR_INPUT
	fInputDeg : LREAL;
END_VAR
VAR
	pi : LREAL := 3.14159265;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_rad2deg := (180/pi)*fInputDeg;]]></ST>
    </Implementation>
    <LineIds Name="F_rad2deg">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>