<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{540b8970-e57b-4c7b-a65e-22bf2965a9b1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN

VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Inputs();
P_MachineControl();
P_AxisControl();
P_Outputs();
P_StablePlatform();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="2" />
      <LineId Id="133" Count="0" />
      <LineId Id="173" Count="0" />
      <LineId Id="154" Count="0" />
      <LineId Id="136" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>